lib/coveralls.rb

Replace the message "Outside the Travis environment" shown when not on a CI with "Outside the CI environment"

Remove explicit reference to Travis

---

coveralls-ruby.gemspec

Some companies [will only use gems with a certain license](https://github.com/rubygems/rubygems.org/issues/363#issuecomment-5079786).
The canonical and easy way to check is [via the gemspec](http://docs.rubygems.org/read/chapter/20#license)
via e.g. 
spec.license = 'MIT'
spec.licenses = ['MIT', 'GPL-2']

Added license to gemspec

---

lib/coveralls/command.rb

Refers to #45
Could you please merge this one, #45, #64, #65, #69 and release a new gem? thanks!

File.exists? is deprecated

---

coveralls-ruby.gemspec

* Strenghtened dependencies as per https://github.com/lemurheavy/coveralls-ruby/pull/61#issuecomment-63805916
* Removed add_runtime_dependency alias in favour of add_dependency

Strengthened dependencies

---

lib/coveralls/configuration.rb

I'm using semaphoreapp for CI and some non-insignficant fraction of the time the message I get from slack is for a really old commit and I'm confident that that the test run didn't use this commit.  I'm not sure how coveralls figures out the correct commit but semaphoreapp is supposed to provide it in environment variables and it looks like there is code to use that sort of setup for a number of CI providers.  This pull request just adds the same for semaphoreapp.

add correct sha details for semaphoreapp

---

lib/coveralls/api.rb

Spaces after columns can be missing the JSON output. Because of that, `repo_token` value is not replaced by `[secure]`. See https://travis-ci.org/amercier/oeco/builds/47742447 as an example.

Fixed repo_token being displayed in clear text

---

.rspec
.travis.yml
Gemfile
coveralls-ruby.gemspec
lib/coveralls/configuration.rb
spec/coveralls/configuration_spec.rb
spec/coveralls/coveralls_spec.rb
spec/coveralls/simplecov_spec.rb

This gem does not specify an explicit minimum Ruby version but there is an implicit minimum Ruby version of 1.9.2, since it depends on `rest-client` 1.7 or greater. I’ve very slightly relaxed this dependency to allow `rest-client` version 1.6.8, which works on Ruby 1.8.7. This will allow the latest version of this library to be installed on Ruby 1.8.7, which is convenient for projects that still run tests against this version of Ruby (even though code coverage will not work). I’ve resorted to [locking to `rest-client` 1.6.8](https://github.com/sferik/twitter/commit/aa6a81d015057196247f681d32e11f962ad71aab) on gems that are still tested against Ruby 1.8.7, which has the effect of installing `coveralls` 0.7.1 (the last version to allow this version of `rest-client`). I have also added Ruby …

Relax rest-client dependency

---

lib/coveralls/configuration.rb
spec/coveralls/configuration_spec.rb

In the case where the entire code base is put through some build process for a PR, `HEAD` of the working tree may not be correct, or it may not even exist.
This allows users to inject PR data into the job _after_ changes are made to the working tree.

allow git configuration through ENV

---

lib/coveralls/api.rb

As I'm working with mime-types 2.x, I'm trying to submit coverage for Ruby 2.x and the code is failing. Part of this is because of a bug with mime-types 2.x (not eliminating `nil` values) and part of this is because the generated tempfile looks like:
`/var/folders/y4/8fxdbz695v52kgdgqdyhxhk80000gq/T/coveralls-upload20140520-38074-1uc3qrtjson`
This change allows it to look like a JSON file based on the extension:
`/var/folders/y4/8fxdbz695v52kgdgqdyhxhk80000gq/T/coveralls-upload20140520-38074-1uc3qrt.json`
This will be compatible for all versions of mime-types.

Let RestClient use MIME::Types properly

---

coveralls-ruby.gemspec

The pessimistic version constraint will allow patch updates to `tins`, e.g., if 1.6.1 is released, without installing `tins` >= 1.7.0, thus maintaining compatibility with Ruby 1.8.7 and Ruby 1.9. I also reverted fa369825e980663220d99726783ba37044f1a3b8, which was not necessary, since there is no required Ruby version specified for `term-ansicolor` itself, so there’s no reason why `term-ansicolor` should be locked to this specific version.

Use ~> to allow tins security patches while remaining compatible with older Ruby versions

---

lib/coveralls/api.rb

Hello,
The api debug information always displays. because `ENV['CI']` is always set.
We do not look at these messages.
The main issue is that this debug text moves our build failures further away from the bottom of our Travis logs. So it gets in the way.
This still shows the api debug information, but just when it is enabled via `ENV['COVERALLS_DEBUG']` or `Coveralls.testing`.
Thanks
---
**before:** (even though debug is turned off)
```
Failed examples:
rspec ./spec/models/metric/capture_spec.rb:76 # Metric::Capture.perf_capture_health_check should queue up realtime capture for vm
Randomized with seed 46205
[Coveralls] Submitting with config:
{
"environment": {
"pwd": "/home/travis/build/ManageIQ/manageiq",
"rails_root": "/home/travis/build/ManageIQ/manageiq",
"simplecov_root": …
```

display api debug only when debug enabled

---

Gemfile
coveralls-ruby.gemspec
lib/coveralls/api.rb
spec/coveralls/simplecov_spec.rb

I'd like to whittle down the list of this gem's dependencies to make it easier to use anywhere.
This change, in particular, will help with some specific apps that are stuck on older versions of rest-client.

Remove RestClient dependency

---

lib/coveralls/api.rb

On line 104, the `Tempfile` class was used but the required file was not required.

require 'tempfile'

---

lib/coveralls/command.rb

- push was using 'exec' to call bash commands
but this function call the bash command into
another process and never back to the ruby
process.
- I change to use the function 'system' for
each bash function, because this function
call the bash command into another process
and before returns to the ruby process

Fix command push

---

lib/coveralls/api.rb

The old code would only work if these gems had already been required, but since you should require this gem before everything else, it doesn't work for a lot of people.
This way guarantees the blocks will be added if the gems are available.

Explicitly try to require webmock and vcr

---

Gemfile
coveralls-ruby.gemspec

Should avoid a warning when running `bundle outdated` on a gem which depends on coveralls
```
$ bundle outdated
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies....
Outdated gems included in the bundle:
* tins (newest 1.11.0, installed 1.6.0)
```

Update tins dependency

---

coveralls-ruby.gemspec

Currently coveralls-ruby fails to install on Ruby < 2.0 due to
term-ansicolor 1.4.0 only supporting Ruby >= 2.0. Changing coveralls-ruby
requirement on term-ansicolor to ~> 1.3.0 will ensure compatiblity.
This patch attempts fixes the problem and brings coveralls in line
with required ruby version >= 1.8.7.

Fix broken support for rubies < 2.0

---

.travis.yml

Now all the tests on ruby 1.9 has failed since `webmock` on which `coverall-ruby` depend stopped supporting ruby 1.9. 
To resolve this situation, this PR updates on `.travis.yml` to ignore the tests on ruby 1.9. 
It should be reconsidered that which ruby versions should be supported by coverall, I think.

Ignore failures on ruby 1.9 since WebMock stopped supporting the version

---

coveralls-ruby.gemspec

Shall we use the `simplecov` latest version 0.16.1?
https://rubygems.org/gems/simplecov

Update simplecov dependency to 0.16.1.

---

coveralls-ruby.gemspec

For allow to use thor v0.20.0.
https://github.com/erikhuda/thor/blob/master/CHANGELOG.md#0200

Relax thor dependency

---

lib/coveralls/configuration.rb
spec/coveralls/configuration_spec.rb

- Using `CI_PIPELINE_ID` as `service_number` allows to post results on the same build.
- [Gitlab build using these commits](https://gitlab.com/graphql-devise/graphql_devise/-/pipelines/282455579).
- [coveralls build with multiple jobs for the same build](https://coveralls.io/builds/38305793)
- `CIRCLE_BUILD_NUM` is different for each job running on a workflow matrix. This might still work for older builds, that's why the same env var is read when not running a workflow.
- [workflow example using these commits](https://app.circleci.com/pipelines/github/graphql-devise/graphql_devise/23/workflows/543c92be-679d-4fcb-8ef1-84bb9cd71204).
- [coveralls build from the workflow above (uses parallel jobs)](https://coveralls.io/builds/38664272).

Fix parallel builds for Gitlab CI and CircleCI
